title = "Eyes And Thumbs"
baseURL = "https://example.com"
languageCode = "en-us"
theme = "ananke"
themesDir = "themes"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 12  # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The Law Society Is Your Enemy"
  facebook = ""
  twitter = "https://twitter.com/SMorpions"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/eyes.jpg"
  recent_posts_number = 5
